#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: excerpts（一些摘抄）
#+date: <2024-11-05 Tue>
#+author: vy
#+email: vyej@
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.5.5)
#+cite_export:
#+LATEX_HEADER:
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/style.css" />

* 2024

** 2024-11 November

*** 2024-11-05 Tuesday
****  Entered on [2024-11-05 Tue 23:26]

尽管洛克不像斯宾诺莎那样爱民主，但是他和斯宾诺莎一样，怀疑那些在自由和平等问题上无法迎合他人的天然骄傲的政治方案或道德教育是否有效。

孟德斯鸠在其巨著的开篇就悄然指出一个根本的形而上学难题，即理智意志（rational conscionsness）的本体论地位问题。

韦伯是知识领域和实践领域毫无联系地并肩共存，而在后者中,责任伦理与良知伦理的各种选择彼此对立，这种态度在他的一生中未曾改变。这使历史变成了一种魔法。
*** 2024-11-22 Friday
**** 
Entered on [2024-11-22 Fri 11:21]

> 那些仍然生活在基督教軌跡中的歷史哲學家們將這一歷史結構稱爲神意（providence），而那些受到啓蒙運動創傷影響的歷史哲學家則將其稱爲理性的狡黠（List cler Vernunft）。不論哪種說法，他們所指的都是一個超越特定人羣計劃的現實——這一現實的起源和目的都是未知的，而且正是由於這一原因，它不可能通過有限的行動而被理解。只有過去已經展開的那部分進程是可知的；而且，可知的程度也僅限於從這一過程本身所產生的認知手段達到的範圍。

歷史的秩序來自秩序的歷史。每個社會都承載着自身的具體境況下創建某種秩序的責任。這種秩序，基於神的或人的目的，將賦予該社會生存的事實以某種意義。尋找可以恰當表達這種意義的符號形式的努力，儘管不完美，卻也不是一系列毫無意義的失敗。這是因爲，從古代近東文明開始，一些偉大的社會創建了一條秩序神序列。各個秩序之間以一種可被理解的方式相互聯接爲朝向一個目標的進步或退化。這個目標就是將關於存在（being）秩序，社會秩序是它的一部分——的真理恰當地符號化。

人們可能將某些方面獲得關於秩序的真理的新見識，但恰恰就是對此種進步的熱情和激情會遮蔽對過去的發現。對以往成就的健忘是最重要的社會現象之一。

然而，就任何一個參與這一過程的特定社會，其秩序中都找不到這種可被理解的歷史結構。它不是一項關於人類或社會行動的計劃，而是一個需要在事件的長河中進行追溯性辨察的現實（reality），這一事件的長河從觀察者所處的現在延伸到無限的將來。
** 2024-12 十二月
*** 2024-12-06 星期五
**** 
Entered on [2024-12-06 周五 00:27]

落了一整個夏天，遠比今夜的這場雨漫長。
樹叢茂盛，懷抱着不易察覺的衰亡。
雨是件衣裳，卻讓人無法溫暖。


*** 2024-12-16 Monday
**** 
Entered on [2024-12-16 Mon 19:16]

It happened that green and crazy summer when Frankie was twelve years old. This was the summer when for a long time she had not been a member. She belonged to nothing in the world. Frankie had become an unjoined person who hung around in doorways, and she was afraid. In June the trees were bright dizzy green, but later the leaves darkened, and the town turned black and shrunken under the glare of the sun. At first Frankie walked around doing one thing and another. The sidewalks of the town were gray in the early morning and at night, but the noon sun put a glaze on them, so that the cement burned and glittered like glass. The sidewalks finally became too hot for frankie's feet, and also she got herself in trouble. She was in so much secret trouble that she thought it was better to stay at home -- and at home there was only Berenice Sadie Brown and John Henry West. The three of them sat at the kitchen table, saying the same things over and over, so that by August the words began to rhyme with each other and sound strange. The world seemed to die each afternoon and nothing moved any longer. At last the summer was like a green sick dream, or like a silent crazy jungle under glass.
*** 2024-12-29 星期日
**** 
Entered on [2024-12-29 周日 00:22]

  只有倒吊男才自稱沙皇。烏鴉不會因爲槍響
  而放棄樹，它們的爪子驟然暴漲，撐破水晶宮殿，
  我臉上壓着倒塌的巨柱
  ——莫非，這就是所謂厄運的重量？
* 2025
** 2025-01 January
*** 2025-01-10 Friday
**** 
Entered on [2025-01-10 Fri 19:04]

我的哲學上的努力在兩個前提下進行。這兩個前提——回想起馬克斯韋伯——是在我與李凱爾特的討論中弄明白的。第一個前提是：科學知識是一切哲理討論中一個不可缺少的因素。今天，沒有科學就不可能有精確性。科學知識的精確性是完全獨立於哲學真理的；但它與後者相關，甚至該說是不能缺少的。另一方面，科學也不能理解它自身爲什麼存在。它不能顯示生活的意義，也不能給予指導。它是有局限的，就它清楚地意識到自己的方法而言，它自己知道這些局限性。

第二個前提是：有一種思維模式，它從科學觀點看來沒有非接受不可的性質也不是普遍有效的，因此它不產生這樣的結果：能聲稱自己作爲可認知性的形式是有效的。這種模式的思維，我們稱之爲哲學思維，它使我導向我的自我本身。它的後果從它自己的程序的內在活動中升發出來；它喚醒我內心的真實本性，最後甚至把意義賦予科學本身。
*** 2025-01-24 Friday
**** 
Entered on [2025-01-24 Fri 21:35]
