title: Notes & Docs
tagline: "研習偉大的著作的過程本身是一種慰藉，我們也沒有其他途徑得以安身立命……因爲意識到了思想的高貴，我們就意識到人類尊嚴的真正基礎以及世界的善。"
description: Moriatur anima meamortem philisophorum.

author:
  name:   vyej
  url:    
  avatar: /assets/img/1.svg

plugins:
  - jekyll-paginate

paginate: 1

categories_path: /categories/
tags_path: /tags/
