title: il y a là cendre
tagline: 
description: Moriatur anima meamortem philisophorum.

author:
  name:   vyej
  url:    
  avatar: /assets/img/1.svg

plugins:
  - jekyll-paginate

paginate: 5

categories_path: /categories/
tags_path: /tags/
