title: Notes & Docs
tagline: "研習偉大的著作的過程本身是一種慰藉，我們也沒有其他途徑得以安身立命……因爲意識到了思想的高貴，我們就意識到人類尊嚴的真正基礎以及世界的善……自由教育在於和最偉大的思想不斷交流的過程，這是一種即使說不上謙卑，也是最爲謙遜的訓練。它同時也是勇氣的訓練：它要求我們與知識分子及其敵人喧囂、浮躁、輕率和低劣的浮華世界測地決裂。它要求我們鼓起勇氣，把普遍接受的觀點僅僅看作是某種意見，或者當成至少與最陌生的和最不受歡迎的觀點一樣，可能是錯誤的極端觀點。自由教育就是爲了把人從庸俗中解放出來，有一個希臘詞很巧妙地表達了‘庸俗’這個意思，他們稱之爲apeirokalia，意爲缺乏對美好事物的體驗。自由教育就是給我們提供對美好事物的體驗。"
description: Moriatur anima meamortem philisophorum.

author:
  name:   vyej
  url:    
  avatar: /assets/img/1.svg

plugins:
  - jekyll-paginate

paginate: 3

categories_path: /categories/
tags_path: /tags/
