name: il y a là cendre
description: 星辰的漫遊構成了時間

url: https://vyej.github.io/
baseurl: '/'

permalink: /:year/:month/:day/:title/
paginate: 1

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
